"""
PDF generation utility for exporting travel itineraries.
Uses fpdf2 to produce a clean, well-formatted PDF document.
"""
from fpdf import FPDF, XPos, YPos
from datetime import datetime
import re


class TravelItineraryPDF(FPDF):
    """Custom FPDF subclass for styled travel itinerary PDFs."""

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_fill_color(37, 99, 235)   # Brand blue
        self.set_text_color(255, 255, 255)
        self.rect(0, 0, 210, 22, "F")
        self.set_y(5)
        self.cell(0, 12, "✈  AI Travel Planner — Trip Itinerary", align="C",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by AI Travel Planner · {datetime.now().strftime('%B %d, %Y')}  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_fill_color(239, 246, 255)
        self.set_text_color(37, 99, 235)
        self.cell(0, 9, f"  {title}", fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        # Strip markdown bold/italic markers before printing
        clean = re.sub(r"\*{1,3}(.*?)\*{1,3}", r"\1", text)
        clean = re.sub(r"#{1,6}\s?", "", clean)
        self.multi_cell(0, 6, clean)
        self.ln(1)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.cell(50, 7, f"{key}:", new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 7, str(value))


def generate_itinerary_pdf(trip_data: dict) -> bytes:
    """
    Generate a PDF itinerary from trip data dict.

    Args:
        trip_data: Dictionary containing all trip information produced by agents.

    Returns:
        Raw PDF bytes ready to be served or saved.
    """
    pdf = TravelItineraryPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── Trip overview ──────────────────────────────────────────
    pdf.section_title("🗺  Trip Overview")
    overview_fields = [
        ("Destination",      trip_data.get("destination", "N/A")),
        ("Travel Dates",     trip_data.get("travel_dates", "N/A")),
        ("Duration",         trip_data.get("duration", "N/A")),
        ("Travelers",        str(trip_data.get("travelers", "N/A"))),
        ("Budget",           trip_data.get("budget", "N/A")),
        ("Trip Style",       trip_data.get("trip_style", "N/A")),
    ]
    for key, val in overview_fields:
        pdf.key_value(key, val)
    pdf.ln(4)

    # ── Itinerary ──────────────────────────────────────────────
    if trip_data.get("itinerary"):
        pdf.section_title("📅  Day-wise Itinerary")
        pdf.body_text(trip_data["itinerary"])

    # ── Budget breakdown ──────────────────────────────────────
    if trip_data.get("budget_plan"):
        pdf.section_title("💰  Budget Breakdown")
        pdf.body_text(trip_data["budget_plan"])

    # ── Hotels ────────────────────────────────────────────────
    if trip_data.get("hotels"):
        pdf.section_title("🏨  Hotel Recommendations")
        pdf.body_text(trip_data["hotels"])

    # ── Transportation ────────────────────────────────────────
    if trip_data.get("transportation"):
        pdf.section_title("🚆  Transportation Options")
        pdf.body_text(trip_data["transportation"])

    # ── Packing checklist ─────────────────────────────────────
    if trip_data.get("packing"):
        pdf.section_title("🎒  Packing Checklist")
        pdf.body_text(trip_data["packing"])

    return bytes(pdf.output())
