"""
PDF generation utility for exporting travel itineraries.
Uses fpdf2 to produce a clean, well-formatted PDF document.
"""
from fpdf import FPDF, XPos, YPos
from fpdf.drawing import DeviceRGB
from datetime import datetime
import re


def _strip_non_latin1(text: str) -> str:
    """Remove characters that cannot be encoded in Latin-1 (e.g. emojis)."""
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class TravelItineraryPDF(FPDF):
    """Custom FPDF subclass for styled travel itinerary PDFs."""

    def header(self):
        # ── Diagonal watermark (drawn first so content sits on top) ───
        self.set_font("Helvetica", "B", 52)
        cx = self.w / 2
        cy = self.h / 2
        # DeviceRGB with a=0.13 gives ~13% opacity watermark
        with self.local_context(text_color=DeviceRGB(0.7, 0.59, 0.35, a=0.13)):
            with self.rotation(35, cx, cy):
                self.set_xy(cx - 65, cy - 12)
                self.cell(130, 24, "AI Travel Planner", align="C")

        # ── Bond-paper warm header bar ─────────────────────────────────
        # Top thin gold-brown accent line
        self.set_fill_color(139, 109, 56)
        self.rect(0, 0, 210, 2, "F")

        # Main parchment/cream band
        self.set_fill_color(245, 235, 210)
        self.rect(0, 2, 210, 22, "F")

        # Title — dark sepia ink
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(80, 55, 20)
        self.set_y(6)
        self.cell(0, 8, "AI Travel Planner", align="C",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Sub-title — muted warm tone
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(130, 100, 55)
        self.cell(0, 5, "Trip Itinerary", align="C",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Bottom divider line
        self.set_draw_color(139, 109, 56)
        self.set_line_width(0.4)
        self.line(10, 26, 200, 26)

        # Reset colours for body content
        self.set_text_color(0, 0, 0)
        self.set_draw_color(0, 0, 0)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 120, 70)
        self.cell(
            0, 10,
            f"Generated by AI Travel Planner  |  "
            f"{datetime.now().strftime('%B %d, %Y')}  |  Page {self.page_no()}",
            align="C",
        )

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(245, 235, 210)       # bond cream
        self.set_text_color(80, 55, 20)          # dark brown
        self.set_draw_color(139, 109, 56)        # gold-brown border
        self.set_line_width(0.3)
        self.cell(0, 8, f"  {_strip_non_latin1(title)}", fill=True, border="B",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(30, 30, 30)
        self.set_draw_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        clean = re.sub(r"\*{1,3}(.*?)\*{1,3}", r"\1", text)
        clean = re.sub(r"#{1,6}\s?", "", clean)
        self.multi_cell(0, 6, _strip_non_latin1(clean))
        self.ln(1)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 55, 20)
        self.cell(50, 7, f"{key}:", new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        remaining = self.epw - 50
        self.multi_cell(remaining, 7, _strip_non_latin1(str(value)))


def generate_itinerary_pdf(trip_data: dict) -> bytes:
    """
    Generate a PDF itinerary from trip data dict.

    Args:
        trip_data: Dictionary containing all trip information produced by agents.

    Returns:
        Raw PDF bytes ready to be served or saved.
    """
    pdf = TravelItineraryPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── Trip overview ──────────────────────────────────────────
    pdf.section_title("Trip Overview")
    overview_fields = [
        ("Destination",  trip_data.get("destination", "N/A")),
        ("Travel Dates", trip_data.get("travel_dates", "N/A")),
        ("Duration",     trip_data.get("duration", "N/A")),
        ("Travelers",    str(trip_data.get("travelers", "N/A"))),
        ("Budget",       trip_data.get("budget", "N/A")),
        ("Trip Style",   trip_data.get("trip_style", "N/A")),
    ]
    for key, val in overview_fields:
        pdf.key_value(key, val)
    pdf.ln(4)

    # ── Itinerary ──────────────────────────────────────────────
    if trip_data.get("itinerary"):
        pdf.section_title("Day-wise Itinerary")
        pdf.body_text(trip_data["itinerary"])

    # ── Budget breakdown ───────────────────────────────────────
    if trip_data.get("budget_plan"):
        pdf.section_title("Budget Breakdown")
        pdf.body_text(trip_data["budget_plan"])

    # ── Hotels ─────────────────────────────────────────────────
    if trip_data.get("hotels"):
        pdf.section_title("Hotel Recommendations")
        pdf.body_text(trip_data["hotels"])

    # ── Transportation ─────────────────────────────────────────
    if trip_data.get("transportation"):
        pdf.section_title("Transportation Options")
        pdf.body_text(trip_data["transportation"])

    # ── Packing checklist ──────────────────────────────────────
    if trip_data.get("packing"):
        pdf.section_title("Packing Checklist")
        pdf.body_text(trip_data["packing"])

    return bytes(pdf.output())
